import type { WishMonitoringView } from '@iwantit/shared';
import type { NotificationPreference, Wish } from '../../database/schema/index.js';
import { describe, expect, it } from 'vitest';
import { AlertEngine } from './alert-engine.js';

const engine = new AlertEngine(); const now = new Date('2026-08-29T12:00:00Z');
const preferences = { priceTargetAlert: true, priceDropAlert: true, newLowAlert: true, stockAlert: true } as NotificationPreference;
describe('AlertEngine', () => {
  it.each([[450, 'Preço desejado atingido!'], [430, 'Preço abaixo do seu objetivo!']] as const)('detects target condition at %s', (price, title) => { const result = engine.evaluate(wish('price_target'), preferences, view(null, null), view(String(price), String(price)), [], now); expect(result).toHaveLength(1); expect(result[0]).toMatchObject({ type: 'price_target', title, metadata: { currentPrice: price, targetPrice: 450 } }); });
  it('detects a relevant drop of at least ten percent', () => { const result = engine.evaluate(wish('price_drop'), preferences, view('600', '600'), view('500', '500'), [], now); expect(result[0]).toMatchObject({ type: 'price_drop', metadata: { previousPrice: 600, currentPrice: 500 } }); });
  it('does not alert for a small drop', () => { expect(engine.evaluate(wish('price_drop'), preferences, view('600', '600'), view('550', '550'), [], now)).toEqual([]); });
  it('detects a new historical low but not the first observation', () => { expect(engine.evaluate(wish('new_low'), preferences, view(null, null), view('500', '500'), [], now)).toEqual([]); const result = engine.evaluate(wish('new_low'), preferences, view('520', '520'), view('480', '480'), [], now); expect(result[0]).toMatchObject({ type: 'new_low', metadata: { previousPrice: 520, currentPrice: 480 } }); });
  it('detects only a reliable unavailable-to-available transition', () => { const transitions = [{ offerId: 'offer', offerUrl: 'https://example.com', marketplaceName: 'Loja', previous: 'unavailable' as const, current: 'available' as const, price: '499.00' }, { offerId: 'new', offerUrl: 'https://example.com/new', marketplaceName: 'Loja', previous: null, current: 'available' as const, price: '400.00' }]; const result = engine.evaluate(wish('back_in_stock'), preferences, view(null, null), view('400', '400'), transitions, now); expect(result).toHaveLength(1); expect(result[0]).toMatchObject({ type: 'back_in_stock', offerId: 'offer' }); });
  it('respects global preferences and the wish-selected rule', () => { expect(engine.evaluate(wish('price_target'), { ...preferences, priceTargetAlert: false }, view(null, null), view('400', '400'), [], now)).toEqual([]); expect(engine.evaluate(wish('new_low'), preferences, view('500', '500'), view('450', '450'), [], now)[0]?.type).toBe('new_low'); });
});
function wish(alertType: Wish['alertType']) { return { id: 'wish', userId: 'user', name: 'Produto real', targetPrice: '450.00', alertType } as Wish; }
function view(current: string | null, historical: string | null): WishMonitoringView { return { wishId: 'wish', targetPrice: '450.00', initialPrice: '699.00', currentLowestPrice: current, currentLowestMarketplace: current ? 'Mercado Livre' : null, historicalLowestPrice: historical, historicalHighestPrice: historical, lastCheckedAt: null, offers: current ? [{ id: 'offer', marketplace: 'mercado-livre', marketplaceName: 'Mercado Livre', externalId: 'MLB1', title: 'Produto real', url: 'https://example.com', imageUrl: null, seller: null, price: current, shippingPrice: '0.00', totalPrice: current, effectivePrice: current, availability: 'available', attributes: {}, checkedAt: now.toISOString(), matchScore: '95.00' }] : [], history: [] }; }
