import { useState, type FormEvent } from 'react';
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { Alert, Button, Input } from '@/components/ui';
import { AuthLayout } from '@/components/auth/AuthLayout';
import { useAuth } from '@/contexts/AuthContext';
import { ApiRequestError } from '@/lib/api';
import { GoogleButton } from '@/components/auth/GoogleButton';

export function LoginPage() {
  const { login, completeTwoFactor, completeGoogleTwoFactor } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [params] = useSearchParams();
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const [challengeToken, setChallengeToken] = useState(''); const googleTwoFactor = params.get('oauth') === 'two_factor';
  const destination = () => (location.state as { from?: string } | null)?.from ?? '/app';
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setLoading(true); const data = new FormData(event.currentTarget); try { const result = await login({ email: String(data.get('email')), password: String(data.get('password')) }); if (result.challengeToken) setChallengeToken(result.challengeToken); else navigate(destination(), { replace: true }); } catch (reason) { setError(reason instanceof ApiRequestError ? reason.message : 'Não foi possível entrar. Tente novamente.'); } finally { setLoading(false); } }
  async function submitCode(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setLoading(true); const code = String(new FormData(event.currentTarget).get('code')); try { await completeTwoFactor(challengeToken, code); navigate(destination(), { replace: true }); } catch (reason) { setError(reason instanceof ApiRequestError ? reason.message : 'Não foi possível verificar o código.'); } finally { setLoading(false); } }
  async function submitGoogleCode(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setLoading(true); const code = String(new FormData(event.currentTarget).get('code')); try { await completeGoogleTwoFactor(code); navigate('/app', { replace: true }); } catch (reason) { setError(reason instanceof ApiRequestError ? reason.message : 'Não foi possível verificar o código.'); } finally { setLoading(false); } }
  const oauthStatus = params.get('oauth'); const oauthMessage = oauthStatus === 'cancelled' ? 'O login com Google foi cancelado.' : oauthStatus === 'error' ? 'Não foi possível concluir o login com Google.' : oauthStatus === 'unavailable' ? 'O login com Google ainda não está configurado.' : '';
  const needsCode = Boolean(challengeToken || googleTwoFactor);
  return <AuthLayout title={needsCode ? 'Confirme que é você.' : 'Que bom ter você de volta.'} subtitle={needsCode ? 'Digite o código exibido no seu aplicativo autenticador.' : 'Entre para acompanhar seus desejos e oportunidades.'} footer={!needsCode && <p>Ainda não tem uma conta? <Link to="/criar-conta">Criar conta</Link></p>}>{needsCode ? <form className="auth-form" onSubmit={googleTwoFactor ? submitGoogleCode : submitCode}>{error && <Alert variant="danger" title="Código não confirmado">{error}</Alert>}<Input label="Código de autenticação" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required placeholder="000000" /><Button type="submit" size="lg" loading={loading}>Confirmar código</Button>{!googleTwoFactor && <Button type="button" variant="ghost" onClick={() => { setChallengeToken(''); setError(''); }}>Voltar</Button>}</form> : <div className="auth-methods">{oauthMessage && <Alert variant={oauthStatus === 'cancelled' ? 'warning' : 'danger'} title="Login com Google">{oauthMessage}</Alert>}<GoogleButton /><div className="auth-divider"><span>ou continue com e-mail</span></div><form className="auth-form" onSubmit={submit}>{error && <Alert variant="danger" title="Não foi possível entrar">{error}</Alert>}<Input label="E-mail" name="email" type="email" autoComplete="email" required placeholder="voce@exemplo.com" /><Input label="Senha" name="password" type="password" autoComplete="current-password" required /><div className="form-link"><Link to="/esqueci-a-senha">Esqueci minha senha</Link></div><Button type="submit" size="lg" loading={loading}>Entrar</Button></form></div>}</AuthLayout>;
}
