import type { ApiMessage, SessionInfo } from '@iwantit/shared';
import { KeyRound, MonitorSmartphone, ShieldCheck, Trash2 } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Alert, Button, Card, Container, Input, Loading } from '@/components/ui';
import { useAuth } from '@/contexts/AuthContext';
import { api, ApiRequestError } from '@/lib/api';

type Setup = { secret: string; uri: string; qrCode: string };
export function SecurityPage() {
  const { user, refresh, logout } = useAuth(); const navigate = useNavigate(); const [sessions, setSessions] = useState<SessionInfo[]>([]); const [setup, setSetup] = useState<Setup | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const loadSessions = () => api<{ sessions: SessionInfo[] }>('/api/auth/sessions').then((result) => setSessions(result.sessions));
  useEffect(() => { void loadSessions(); }, []);
  async function startSetup(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); try { const password = new FormData(event.currentTarget).get('password'); setSetup(await api('/api/auth/2fa/setup', { method: 'POST', body: JSON.stringify({ password }) })); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } }
  async function enable(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); try { const code = new FormData(event.currentTarget).get('code'); const result = await api<ApiMessage>('/api/auth/2fa/enable', { method: 'POST', body: JSON.stringify({ code }) }); setSetup(null); setMessage(result.message); await refresh(); await loadSessions(); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } }
  async function disable(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); const data = new FormData(event.currentTarget); try { const result = await api<ApiMessage>('/api/auth/2fa/disable', { method: 'POST', body: JSON.stringify({ password: data.get('password'), code: data.get('code') }) }); setMessage(result.message); await refresh(); await loadSessions(); event.currentTarget.reset(); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } }
  async function revoke(session: SessionInfo) { await api(`/api/auth/sessions/${session.id}`, { method: 'DELETE' }); if (session.current) { await logout(); navigate('/entrar', { replace: true }); } else await loadSessions(); }
  return <main className="security-page"><header className="site-header"><Container className="header-inner"><Link className="brand" to="/app">← Voltar</Link><span className="security-badge"><ShieldCheck aria-hidden="true" /> Segurança</span></Container></header><Container className="security-content"><div className="section-heading"><div><span className="section-kicker">Proteção da conta</span><h1>Segurança e sessões</h1></div><p>Controle o segundo fator e os dispositivos conectados à sua conta.</p></div>{message && <Alert variant="success" title="Alteração concluída">{message}</Alert>}{error && <Alert variant="danger" title="Não foi possível concluir">{error}</Alert>}<div className="security-grid"><Card className="security-card"><div className="security-card__title"><KeyRound aria-hidden="true" /><div><h2>Autenticação em dois fatores</h2><p>{user?.twoFactorEnabled ? 'Ativada' : 'Desativada'}</p></div></div>{user?.twoFactorEnabled ? <form className="auth-form" onSubmit={disable}><Input label="Senha atual" name="password" type="password" autoComplete="current-password" required /><Input label="Código do autenticador" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required /><Button variant="danger" loading={loading}>Desativar 2FA</Button></form> : setup ? <div className="totp-setup"><img src={setup.qrCode} alt="QR Code para configurar o aplicativo autenticador" /><p>Escaneie o QR Code ou informe esta chave:</p><code>{setup.secret}</code><form className="auth-form" onSubmit={enable}><Input label="Código de confirmação" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required /><Button loading={loading}>Confirmar e ativar</Button></form></div> : <form className="auth-form" onSubmit={startSetup}><p className="security-help">Confirme sua senha antes de vincular um aplicativo autenticador.</p><Input label="Senha atual" name="password" type="password" autoComplete="current-password" required /><Button loading={loading}>Configurar 2FA</Button></form>}</Card><Card className="security-card"><div className="security-card__title"><MonitorSmartphone aria-hidden="true" /><div><h2>Sessões ativas</h2><p>{sessions.length} dispositivo(s)</p></div></div>{sessions.length === 0 ? <Loading label="Carregando sessões" /> : <div className="session-list">{sessions.map((session) => <div className="session-item" key={session.id}><div><strong>{session.current ? 'Este dispositivo' : session.device || 'Dispositivo desconhecido'}</strong><span>{session.ip || 'IP indisponível'} · até {new Date(session.expiresAt).toLocaleDateString('pt-BR')}</span></div><Button variant="ghost" size="sm" onClick={() => revoke(session)} aria-label="Encerrar sessão"><Trash2 aria-hidden="true" /></Button></div>)}</div>}</Card></div></Container></main>;
}

function errorMessage(reason: unknown) { return reason instanceof ApiRequestError ? reason.message : 'Tente novamente em alguns instantes.'; }
